services:
  backend:
    build: .
    ports:
      - "8001:8001"  # Измените порт, если ваш сервер слушает другой
    volumes:
      - .:/app  # Для разработки - монтируем код
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
       - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge